routes/web.php
<?php

use Illuminate\Support\Facades\Route;
Auth::routes();

Route::get('/lang/{lang}', [App\Http\Controllers\HomeController::class, 'lang'])->name('lang');
Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/search', [App\Http\Controllers\HomeController::class, 'search'])->name('search');
Route::get('/about', [App\Http\Controllers\HomeController::class, 'about'])->name('about');
Route::post('/subscribe', [App\Http\Controllers\SubscriberController::class, 'store'])->name('subscribe');
Route::post('/basket/{id}/{sign}', [App\Http\Controllers\BasketController::class, 'update'])->where('sign', 'p|m');
Route::get('/basket', [App\Http\Controllers\BasketController::class, 'index'])->name('basket.index');
Route::get('/getBasketData', [App\Http\Controllers\BasketController::class, 'getBasketData']);
Route::get('/books', [App\Http\Controllers\BookController::class, 'catalog'])->name('books.index');
Route::get('/books/{book}', [App\Http\Controllers\BookController::class, 'show'])->name('books.show');
Route::group([
    'prefix'        => '/cabinet',
    'middleware'    => ['auth'],
    'as'            => 'cabinet.'
], function(){
    Route::get('/', [App\Http\Controllers\CabinetController::class, 'index'])->name('index');
    Route::get('/account', [App\Http\Controllers\CabinetController::class, 'account'])->name('account');
    Route::post('/account', [App\Http\Controllers\CabinetController::class, 'accountUpdate'])->name('account.update');
    Route::view('calculator', 'cabinet.calculator')->name('calculator');
    Route::view('course', 'cabinet.cource')->name('course');
    Route::post('/connect', [App\Http\Controllers\CabinetController::class, 'TronAddressUpdate'])->name('tron.update');
});
Route::group([
    'prefix' => '/user',
    'middleware' => ['auth'],
    'as' => 'user.'
], function(){
    Route::get('/profile', [App\Http\Controllers\UserController::class, 'profile'])->name('profile.show');
    Route::post('/profile', [App\Http\Controllers\UserController::class, 'profileUpdate'])->name('profile.update');
});
Route::group([
    'prefix' => '/admin',
    'middleware' => ['auth', 'manager'],
    'as' => 'admin.'
], function(){
    Route::view('/', 'admin.index')->name('index');
    Route::resources([
        'orders' => App\Http\Controllers\OrderController::class,
        'partners' => App\Http\Controllers\PartnerController::class,
        'posts' => App\Http\Controllers\PostController::class,
        'books' => App\Http\Controllers\BookController::class,
        'categories' => App\Http\Controllers\CategoryController::class,
        'slides' => App\Http\Controllers\SlideController::class,
        'subscribers' => App\Http\Controllers\SubscriberController::class,
    ]);
});
Route::group([
    'prefix' => '/admin',
    'middleware' => ['auth', 'admin'],
    'as' => 'admin.'
], function(){
    Route::resources([
        'users' => App\Http\Controllers\UserController::class
    ]);
});
Route::post('/posts/{post}/comment', [App\Http\Controllers\PostController::class, 'comment'])->name('posts.comment');
Route::get('/{category}', [App\Http\Controllers\CategoryController::class, 'show'])->name('categories.show');
Route::get('/{category}/{post}', [App\Http\Controllers\PostController::class, 'show'])->name('posts.show');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;
    protected $fillable = [ 'name', 'email', 'password', 'active', 'photo', 'manager'];

    protected $hidden = [
        'password',
        'remember_token',
    ];
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use Storage;
class UserController extends Controller
{
    public function index(){
        $users = User::paginate(50);
        return view('admin.users.index', compact('users'));
    }
    public function edit(User $user){
        return view('admin.users.edit', compact('user'));
    }
    public function profile(){
        $user = auth()->user();
        return view('users.profile', compact('user'));
    }
    public function create(){
        return view('admin.users.create');
    }
    public function store(Request $request){
        $request->validate([
            'name'  => 'required|string|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'nullable|confirmed|string|max:255|min:6'
        ]);
        $data = $request->except('photo', 'password');
        $data['manager'] = $request->has('manager');
        $data['active'] = $request->has('active');
        $data['password']   = bcrypt($request->password);
        if($request->hasFile('photo')){
            $data['photo'] = $request->file('photo')->store('users');
        }
        User::create($data);
        session()->flash('success', 'Новый пользователь успешно добавлен');
        return redirect()->route('admin.users.index');
    }
    public function update(Request $request, User $user){
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email|max:255|unique:users,id,' . $user->id,
            'password' => 'nullable|confirmed|string|max:255|min:6'
        ]);
        $data = $request->except('password');
        $data['active'] = $request->has('active');
        $data['manager'] = $request->has('manager');
        if($request->password) $data['password'] = bcrypt($request->password);
        if($request->hasFile('photo')){
            if($user->photo) Storage::delete($user->photo);
            $data['photo'] = $request->file('photo')->store('users');
        }
        $user->update($data);
        session()->flash('success', 'Данные пользователя успешно обновлены');
        return back();
    }
    public function destroy(User $user){
        if($user->id == 1) abort(403);
        if($user->photo) Storage::delete($user->photo);
        $user->delete();
        session()->flash('success', 'Пользователь успешно удален');
        return back();
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col">Новый пользователь</div>
    <div class="col text-right"><a href="{{route('admin.users.index')}}" class="btn btn-sm btn-primary"><i class="fa fa-arrow-left"></i></a></div>
</div>
<hr>
<form action="{{route('admin.users.store')}}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-md-6">
            <div class="form-group form-check">
                <input name="active" type="checkbox" class="form-check-input" id="active" @if(old('active')) checked @endif>
                <label class="form-check-label" for="active">Активен</label>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group form-check">
                <input name="manager" type="checkbox" class="form-check-input" id="manager" @if(old('manager')) checked @endif>
                <label class="form-check-label" for="manager">Менеджер</label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label>Имя</label>
                <input type="text" class="form-control form-control-sm @error('name') is-invalid @enderror" name="name" value="{{old('name')}}">
                @error('name') <span class="invalid-feedback">{{$message}}</span> @enderror
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label>E-mail</label>
                <input type="email" class="form-control form-control-sm @error('email') is-invalid @enderror" name="email" value="{{old('email')}}">
                @error('email') <span class="invalid-feedback">{{$message}}</span> @enderror
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label>Пароль</label>
                <input type="password" class="form-control form-control-sm @error('password') is-invalid @enderror" name="password">
                @error('password') <span class="invalid-feedback">{{$message}}</span> @enderror
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label>Подтвердите пароль</label>
                <input type="password" class="form-control form-control-sm" name="password_confirmation">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label class="d-block">Фото</label>
                <input type="file" name="photo">
            </div>
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-sm btn-success">Сохранить</button>
    </div>
</form>
@stop

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col">Редактирование пользователя</div>
    <div class="col text-right"><a href="{{route('admin.users.index')}}" class="btn btn-sm btn-primary"><i class="fa fa-arrow-left"></i></a></div>
</div>
<hr>
<form action="{{route('admin.users.update', $user->id)}}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="row">
        <div class="col-md-6">
            <div class="form-group form-check">
                <input name="active" type="checkbox" class="form-check-input" id="active" @if($user->active) checked @endif>
                <label class="form-check-label" for="active">Активен</label>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group form-check">
                <input name="manager" type="checkbox" class="form-check-input" id="manager" @if($user->manager) checked @endif>
                <label class="form-check-label" for="manager">Менеджер</label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label>Имя</label>
                <input type="text" class="form-control form-control-sm" name="name" value="{{old('name', $user->name)}}">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label>E-mail</label>
                <input type="email" class="form-control form-control-sm" name="email" value="{{old('email', $user->email)}}">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label>Пароль</label>
                <input type="password" class="form-control form-control-sm" name="password">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label>Подтвердите пароль</label>
                <input type="password" class="form-control form-control-sm" name="password_confirmation">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label class="d-block">Фото</label>
                <input type="file" name="photo">
            </div>
        </div>
        <div class="col-md-6">
            @if($user->photo)
            <img src="/storage/{{$user->photo}}" alt="{{$user->name}}" class="img-fluid">
            @endif
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-sm btn-success">Сохранить</button>
    </div>
</form>
@stop

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="d-flex align-items-center justify-content-between">
        <span>Список пользователей</span>
        <span><a href="{{route('admin.users.create')}}" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i> Добавить пользователя</a></span>
    </div>
    {{$users->links()}}
    <table class="table">
        <tr>
            <th>Имя</th>
            <th>E-mail</th>
            <th width="100px">
        </tr>
        @foreach($users as $item)
        <tr>
            <td>{{$item->name}}</td>
            <td>{{$item->email}}</td>
            <td>
                <a href="{{route('admin.users.edit', $item->id)}}" class="btn btn-sm btn-info"><i class="fa fa-pencil"></i></a>
                <form action="{{route('admin.users.destroy', $item->id)}}" class="d-inline-block confirmed" method="post">
                    @csrf
                    <input type="hidden" name="_method" value="DELETE">
                    <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    {{$users->links()}}
@stop